### ISSUE TITLE
[UI] Drop dependency on fidget.nvim?

### ISSUE THREAD

**Issue by xsh005** [nvim-neorocks/rocks.nvim#108]
`fidget.nvim`, while quite nice, is more than just a notification framework, it would be nice if it can be decoupled. I just wrote my own `vim.notify` which has a similar look and feel to fidget, if no one is against this I am interested in a pr.

**Comment by mrcjkb** [comment]
Hey 👋 

We don't use fidget.nvim as a notification framework, but as a progress framework, for which afaik neovim currently has no built-in API.

**Comment by mrcjkb** [comment]
One thing we've considered is to extract the progress handler into an adapter, for which we could expose an API to override the default fidget-based implementation.

**Comment by xsh005** [comment]
> We don't use fidget.nvim as a notification framework, but as a progress framework, for which afaik neovim currently has no built-in API.

Ah, excuse my wording :smile: 

A progress framework is really just updating a floating window, which could be achieved with some [200 LOC](https://github.com/xiaoshihou514/NanoVim/blob/main/lua/nano/module/ui/notify.lua), it just occurs really unfortunate that we would need such a heavy dependency :cry:

**Comment by mrcjkb** [comment]
I don't see an issue with depending on fidget.nvim. It doesn't add any overhead to neovim, since we only use its progress API and don't call its `setup` function or add it to the runtimepath.

**Comment by xsh005** [comment]
Hmm, I guess you are right, didn't thought of that!
