### ISSUE TITLE
[Bug] Invalid directory name generated by installation script

### ISSUE THREAD

**Issue by haruleekim** [nvim-neorocks/rocks.nvim#117]
https://github.com/nvim-neorocks/rocks.nvim/blob/33d852102566c57575946564006e2dcb8f472a6b/installer.lua#L157

The code `vim.loop.random(7)` in the above possibly generates a directory name that is treated as invalid by the OS.
For example: `luarocks-<a1><ec>^O<98>^^{<f8>`.

Therefore, I suggest changing that line to the following:
```lua
local tempdir = vim.fs.joinpath(vim.fn.stdpath("run"), string.format("luarocks-%X", math.random(256 ^ 7)))
```

**Comment by mrcjkb** [comment]
Hey :wave:
Thanks for reporting!

Your proposed solution looks reasonable to me. @vhyrro what do you think?
