### ISSUE TITLE
[Bug] Plugin dependencies added to `rocks.toml` when updated

### ISSUE THREAD

**Issue by NTBBloodbath** [nvim-neorocks/rocks.nvim#140]
As the title says, whenever a plugin dependency gets updated through `:Rocks update`, it is added as a new entry to the `rocks.toml` entry, causing some unexpected junk entries.

This one is a bit more hard to reproduce so I cannot really give reliable reproduction steps here, hope it's not a blocker!

**Comment by mrcjkb** [comment]
@NTBBloodbath can you add some of the junk entries that were added? :pray:

**Comment by NTBBloodbath** [comment]
Uhh one example could be `nvim-nio` which recently got an update and it's one of our dependencies.

The `rocks.toml` looks something like this after running `:Rocks update`:

```toml
[plugins]
# .....
nvim-nio = "1.6.0"
```

If you remove the newly added `nvim-nio` entry nothing happens, so it's not something that can be reproduced over and over again so I guess testing will be hard for this one 🫠
