### ISSUE TITLE
About `init` function

### ISSUE THREAD

**Issue by jinzhongjia** [nvim-neorocks/rocks.nvim#19]
https://github.com/nvim-neorocks/rocks.nvim/blob/5faf2bed7362b71d6a00f89ddb428070ff0eb6bc/lua/rocks/init.lua#L30

The `wait` here does not exist, which will cause the plug-in initialization to fail.

**Comment by mrcjkb** [comment]
Which version of Neovim are you using? This was written for Neovim 0.10 (nightly).

`luarocks.cli` returns the result of its underlying call to `vim.system`, which is a `vim.SystemObject`. A `vim.SystemObject` has a `:wait()` function.

Anyway, the install process is going to change, and the `bootstrap_install` will be removed.

**Comment by jinzhongjia** [comment]
I am using nightly, but it seems that if the network is not good, the installation of dependencies will fail.

**Comment by jinzhongjia** [comment]
Everything is normal now. By the way, the installation method of readme has not been completed yet, right?
I am currently using a method similar to lazy to install it.

**Comment by jinzhongjia** [comment]
I found that luarocks will fail to install toml-edit. 
When I try to install it through the command line, the following prompt appears:
![image](https://github.com/nvim-neorocks/rocks.nvim/assets/41784264/18763812-1d10-49fe-af72-8da5f262cd84)

**Comment by mrcjkb** [comment]
Yes, this is still very much WIP 😅

It looks like you have lua 5.4 installed, and it's trying to find toml-edit for that version.
Neovim uses luaJIT (with lua 5.1 compatibility), so you'll need one of those lua versions.

Which platform are you on?

**Comment by jinzhongjia** [comment]
I work in arch under wsl2

**Comment by jinzhongjia** [comment]
maybe I can install this? https://aur.archlinux.org/packages/lua51-luarocks-build-rust-mlua

**Comment by jinzhongjia** [comment]
> maybe I can install this? https://aur.archlinux.org/packages/lua51-luarocks-build-rust-mlua

no effect

**Comment by jinzhongjia** [comment]
I tried this, https://aur.archlinux.org/packages/lua-luarocks-build-rust-mlua
it works

**Comment by mrcjkb** [comment]
> I work in archlinux under wsl2, I checked the official library of archlinux and the dependency of luarocks is lua5.4

That sounds like a packaging "bug" on the Arch Linux side. luarocks can run with any lua version between 5.1 and 5.4 (and luaJIT).
I guess you can still install lua 5.1. This plugin configures luarocks to use lua 5.1, but that won't work if it isn't installed.

**Comment by NTBBloodbath** [comment]
> I found that luarocks will fail to install toml-edit. When I try to install it through the command line, the following prompt appears: ![image](https://user-images.githubusercontent.com/41784264/279300029-18763812-1d10-49fe-af72-8da5f262cd84.png)

The same thing happened to me a couple of days ago, can you check what your `luarocks config` returns? Your `lua_version` should point to `5.1` and it seems like it _could be_ pointing to `5.4`. This causes the dependency to be installed correctly, but luarocks cannot recognize it because it looks for it in the wrong directory. Being honest, luarocks should search under the same version that is specified in the CLI but that is already upstream, nothing that can be done from this side :(

**Comment by jinzhongjia** [comment]
lua5.1 and lua5.4 can coexist on my computer, but `luarocks config` outputs 5.4

**Comment by jinzhongjia** [comment]
But when I specify lua-version is 5.1, its output is 5.1

**Comment by jinzhongjia** [comment]
here is 5.4 output https://gist.github.com/jinzhongjia/0b1acc55bebd5a56a7e17f9a9df6f53e

5.1 output https://gist.github.com/jinzhongjia/bcfbda053813f8e2e8e3236e9b811cf8

**Comment by NTBBloodbath** [comment]
Honestly, I have no idea now. Everything looks correct and I took a look at the luarocks code that has to do with the configuration to see if I found something but everything is fine.

There are some issue reports with the same dependency in the luarocks repository with other projects but unfortunately none have had any response with a proper solution from the luarocks maintainers, [here](https://github.com/luarocks/luarocks/issues/1509) is an example of them and in [this](https://github.com/luarocks/luarocks/issues/1521) other one, even though it is another use case, the same thing happens and ultimately, it seems to be an internal luarocks bug with their build system in some edge cases like this one where a custom builder is being used for the dependencies 😥

**Comment by NTBBloodbath** [comment]
Update: could you open a separate issue to track the problem when trying to install toml-edit using luarocks? That way everything would be more organized and the original problem of this issue seems to have been solved. Thanks in advance!

Ps: I think that following a suggestion made by @mrcjkb we could solve it _and also eliminate some dependencies such as requiring having Rust installed_, we are going to investigate further on this one.

**Comment by jinzhongjia** [comment]
ok, I will open a new issue
