### ISSUE TITLE
Installer failed due to syntax error

### ISSUE THREAD

**Issue by scottbenjamin** [nvim-neorocks/rocks.nvim#205]
I tried the installation and experienced:

`Error detected while processing command line..SourceCmd Autocommands for "https://*"..function netrw#NetSource[21]..script /tmp/nvim.scott/wDwVML/0.lua:
E5112: Error while creating lua chunk: /tmp/nvim.scott/wDwVML/0.lua:189: '}' expected (to close '{' at line 187) near '"configure"'
Press ENTER or type command to continue`

There is a missing `,` on line 189.

**Comment by rodhash** [comment]
+1
