### ISSUE TITLE
luarocks installed with an error on android (Termux Environment)

### ISSUE THREAD

**Issue by amsitlab** [nvim-neorocks/rocks.nvim#208]
luarocks has been installed on `~/.local/share/nvim/rocks` by typing `nvim -u NORC -c "source installer.lua` with following an error for next execution
FYI: luarocks for termux have an patch for their environment please see [here](https://github.com/termux/termux-packages/tree/master/packages/luarocks) for details if rocks.nvim want to support neovim user on android
thanks

**Comment by amsitlab** [comment]
> We can look into it, but I'm sure there will be some more issues down the line. rocks.nvim depends on [toml-edit](https://luarocks.org/modules/neorg/toml-edit), which requires a rust toolchain to compile.

Don't worry about that, [Termux](https://termux.dev) have rust package on their repository

**Comment by mrcjkb** [comment]
I don't think the rocks.nvim install script applying the termux patches is a viable option.
But I believe you should be able to install rocks.nvim if you have luarocks installed, and deselect the "Set up luarocks" option in the installer?

Maybe it's also a good idea to deselect the option by default if we can detect a correctly configured installation.

**Comment by mrcjkb** [comment]
Closing, as it's not feasible for us to support termux.
See the [manual installation guide in the wiki](https://github.com/nvim-neorocks/rocks.nvim/wiki/Installing-rocks.nvim-manually,-without-the-installation-script).
