### ISSUE TITLE
Missing dependencies / prerequisits in readme

### ISSUE THREAD

**Issue by tilupe** [nvim-neorocks/rocks.nvim#226]
Hi,

I wanted to try to use the installation script but ran first into an error, that there is no lua 5.1 and afterwards that it couldn't find a lua.h file.

Not sure if I did something wrong but it would have been much easier if there was written, that I need install lua5.1 and liblua5.1-dev (on debian based linux).

Thanks for the plugin looking forward to try it out

**Comment by mrcjkb** [comment]
Thanks for the input :smile: 

I've updated the readme.
