### ISSUE TITLE
Nvim no longer opens after installing rocks.

### ISSUE THREAD

**Issue by Tvrt1e** [nvim-neorocks/rocks.nvim#231]
nvim -v:
NVIM v0.10.0-dev-2594+g4de4f13eb
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188

I installed rocks using the installer and followed directions. Afterward whenever I open nvim I get nothing but a bunch of white space in terminal and it brings me back to shell prompt. I also tried installing rocks manually and got the exact same behavior. The only thing I could think to be the issue is the fact that I'm using a lua heredoc in my init.vim as opposed to using an init.lua. If this is the problem is there any way to install rocks without a lua vimrc?

**Comment by mrcjkb** [comment]
Hey 👋 

Possibly a duplicate of

**Comment by Tvrt1e** [comment]
That was it, thank you. Not too good with computers so I saw a bunch of stuff I didn't understand and assumed it didn't apply.
