### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by CRAG666** [nvim-neorocks/rocks.nvim#232]
Installing rocks.nvim...
Installing rocks.nvim failed:                                                                                         
stderr: Warning: Failed searching manifest: Failed loading manifest for https://nvim-neorocks.github.io/rocks-binaries
/: /home/think-crag/.cache/luarocks/https___nvim-neorocks.github.io_rocks-binaries/manifest-5.1: No such file or direc
tory                                                                                                                  
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting /home/think-crag/.cache/luarock
s/https___luarocks.org/manifest-5.1.zip                                                                               
Warning: Failed searching manifest: Failed loading manifest for https://raw.githubusercontent.com/rocks-moonscript-org
/moonrocks-mirror/master/: /home/think-crag/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moo
nrocks-mirror_master/manifest-5.1: No such file or directory                                                          
Warning: Failed searching manifest: Failed loading manifest for https://loadk.com/luarocks/: /home/think-crag/.cache/l
uarocks/https___loadk.com_luarocks/manifest-5.1: No such file or directory                                            
                                                                                                                      
Error: No results matching query were found for Lua 5.1.                                                              
To check if it is available for other Lua versions, use --check-lua-versions.                                         
                                                                                                                      
stdout:

**Comment by mrcjkb** [comment]
Hey 👋 

We need a little more context:

- Which operating system/version are you using?
- Which installer options have you selected? E.g., are you using a preinstalled luarocks, or are you letting the installer set up luarocks for you?

Based on the error message, it looks like luarocks is having problems with its cache. Have you tried deleting the `/home/think-crag/.cache/luarock
s/` directory?

**Comment by CRAG666** [comment]
OS: Arch linux
Installa: Readme
/usr/bin/luarocks 3.11.0
LuaRocks main command-line interface

**Comment by CRAG666** [comment]
@mrcjkb thanks

**Comment by CRAG666** [comment]
install command: nvim -u NORC -c "source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"

**Comment by CRAG666** [comment]
For some reason the manifests are downloaded to my home 
![imagen](https://github.com/nvim-neorocks/rocks.nvim/assets/34254373/76971c70-29bb-41c2-806b-7e8f693bd95e)

**Comment by mrcjkb** [comment]
:thinking: it seems like your luarocks config might be interfering with something.
Can you try with `LUAROCKS_CONFIG="" nvim -u NORC -c "source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"`?

**Comment by CRAG666** [comment]
@mrcjkb Installing rocks.nvim...                                                                                    
Installing rocks.nvim failed:                                                                                         
stderr: Warning: Failed searching manifest: Failed loading manifest for https://nvim-neorocks.github.io/rocks-binaries
/: /home/think-crag/.cache/luarocks/https___nvim-neorocks.github.io_rocks-binaries/manifest-5.1: No such file or direc
tory                                                                                                                  
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting /home/think-crag/.cache/luarock
s/https___luarocks.org/manifest-5.1.zip                                                                               
Warning: Failed searching manifest: Failed loading manifest for https://raw.githubusercontent.com/rocks-moonscript-org
/moonrocks-mirror/master/: /home/think-crag/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moo
nrocks-mirror_master/manifest-5.1: No such file or directory                                                          
Warning: Failed searching manifest: Failed loading manifest for https://loadk.com/luarocks/: /home/think-crag/.cache/l
uarocks/https___loadk.com_luarocks/manifest-5.1: No such file or directory                                            
                                                                                                                      
Error: No results matching query were found for Lua 5.1.                                                              
To check if it is available for other Lua versions, use --check-lua-versions.                                         
                                                                                                                      
stdout:

**Comment by mrcjkb** [comment]
Since your luarocks binary is in `/usr/bin/luarocks`, I'm assuming your are using a local install (not configured by the rocks.nvim installer. There appears to be an issue with your luarocks installation, possibly related to https://github.com/luarocks/luarocks/issues/952.

**Comment by CRAG666** [comment]
Uninstall luarocks, and excecute intructions in readme: 
Installing rocks.nvim...                                                                                      
Installing rocks.nvim failed:                                                                                         
stderr: Warning: Failed searching manifest: Failed loading manifest for https://nvim-neorocks.github.io/rocks-binaries
/: /home/think-crag/.cache/luarocks/https___nvim-neorocks.github.io_rocks-binaries/manifest-5.1: No such file or direc
tory                                                                                                                  
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting /home/think-crag/.cache/luarock
s/https___luarocks.org/manifest-5.1.zip                                                                               
Warning: Failed searching manifest: Failed loading manifest for https://raw.githubusercontent.com/rocks-moonscript-org
/moonrocks-mirror/master/: /home/think-crag/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moo
nrocks-mirror_master/manifest-5.1: No such file or directory                                                          
Warning: Failed searching manifest: Failed loading manifest for https://loadk.com/luarocks/: /home/think-crag/.cache/l
uarocks/https___loadk.com_luarocks/manifest-5.1: No such file or directory                                            
                                                                                                                      
Error: No results matching query were found for Lua 5.1.                                                              
To check if it is available for other Lua versions, use --check-lua-versions.

**Comment by CRAG666** [comment]
Command: LUA_BINDIR="/bin" LUA_BINDIR_SET=yes nvim -u NORC -c "source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"
Configuring luarocks...
Configuring luarocks failed.                                                                                          
stderr:                                                                                                               
stdout:                                                                                                               
Configuring LuaRocks version dev...                                                                                   
                                                                                                                      
Lua interpreter found: /bin/luajit                                                                                    
Checking if /bin/luajit is Lua version 5.1... yes                                                                     
lua.h for Lua 5.1 not found (tried //include/lua/5.1/lua.h //include/lua5.1/lua.h //include/lua-5.1/lua.h //include/lu
a51/lua.h //include/lua.h //include/luajit-2.1/lua.h)                                                                 
                                                                                                                      
If the development files for Lua (headers and libraries)                                                              
are installed in your system, you may need to use the                                                                 
--with-lua or --with-lua-include flags to specify their location.                                                     
                                                                                                                      
If those files are not yet installed, you need to install                                                             
them using the appropriate method for your operating system.                                                          
                                                                                                                      
Run ./configure --help for details on flags.                                                                          
                                                                                                                      
configure failed.

**Comment by mrcjkb** [comment]
In the luarocks issue I linked, the comments say it's an issue with your wget installation.

You can try one of the following:

- Upgrade wget (make sure it's a full-featured version).
- Modify your luarocks installation to use curl (see [this comment](https://github.com/luarocks/luarocks/issues/952#issuecomment-1627595329)).
