### ISSUE TITLE
[Feature]: `includes` option for splitting rocks.toml

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks.nvim#240]
I haven't quite thought through the complexities of this implementation, but it's an interesting idea...

As configuration files get large, it would be nice to be able to split it up into several subfiles (smaller TOML files).

rocks-include.nvim would parse the original rocks.toml, look for any `include` or `includes` statements and attempt to replace their occurences with the content of the target include files.

Any ideas can be brainstormed on this thread.

**Comment by teto** [comment]
another possibility is to do like on linux and load all files in a `rocks.d/` folder

**Comment by mrcjkb** [comment]
This has been closed by #565.
