### ISSUE TITLE
[Feature] Prompt to sync rocks if plugins cannot be loaded at startup

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#293]
With https://github.com/nvim-neorocks/rocks.nvim/pull/292, rocks.nvim shows a warning if plugins could not be loaded at startup.

We could also prompt to run `:Rocks sync`.

**Comment by NTBBloodbath** [comment]
question: could we also add an entry to the `vim.g.rocks_config` to also automate this process if wanted instead of prompting for confirmation?

**Comment by mrcjkb** [comment]
> question: could we also add an entry to the `vim.g.rocks_config` to also automate this process if wanted instead of prompting for confirmation?

Sounds like a good idea.

**Comment by tombh** [comment]
I just did a re-install and so the prompt to run `Rocks sync`! Niiice ✨

Regarding #612, do you think there might be a way to run it from the bootstrap script? So that there's no need to restart Neovim to see all the plugins load? This is very low priority.

**Comment by mrcjkb** [comment]
I think you could add a `vim.cmd.Rocks("sync")` after sourcing the bootstrap script in your `init.lua` 😄

**Comment by tombh** [comment]
I did try that, well at least I put it at the end of the `if not pcall(require, "rocks") then` block, and I just get `command not found: Rocks`. And then once Neovim's boot sequence is outside of that block I'm not sure how to tell if it's a first time bootstrap or not. But I'm not even sure when in the boot sequence `vim.cmd.Rock` would be available?

**Comment by mrcjkb** [comment]
Ah right, the command doesn't exist at the time the bootstrap script is run. 
That also means we can't run `Rocks sync` within the bootstrap script.

Although, I find it strange that it isn't prompting you for a sync unless you restart - which indicates that nvim isn't sourcing the rocks.nvim plugin script and you may have to add it to the runtimepath again after sourcing the bootstrap script.

**Comment by tombh** [comment]
Ah, what I mean by the restart is that, once `Rocks sync` has finished, none of the plugins are actually loaded. Neovim has to be restarted on order for the plugins to load.

Like I say this is a very minor issue.

**Comment by mrcjkb** [comment]
By default, rocks.nvim should try to load plugins after a `sync`, unless the `dynamic_rtp` option is set to `false` (it defaults to `true`).
However, it only adds the plugins to the runtimepath and loads plugin scripts.
If a plugin requires a `setup` function to be initialised (which is a common [antipattern in the neovim community](https://mrcjkb.dev/posts/2023-08-22-setup.html)), rocks.nvim won't automatically call that.

**Comment by tombh** [comment]
I read your post and learnt a lot, thanks. This is why I want to give Rocks a go, to try to be part of some better practices. So I'm fine with some pain points if it supports progress in the ecosystem.

Also I'm sure my neighbours will be happier now that my Neovim isn't randomly launching so many nuclear warheads 😅
![image](https://github.com/user-attachments/assets/1f52d2ff-2a57-4941-8f75-ad65d8a60bf3)

So if I'm understanding right, Rocks _is_ re-loading plugins after a `sync`, but it isn't calling any `.setup()`s, because it's considered bad practice to initialise your plugin with a function. So ideally, if I want my plugins to be automatically loaded, then I should bring it up with the plugins authors.

**Comment by mrcjkb** [comment]
Whether or not to use `setup` is somewhat a hot topic in the plugin community, with some plugin authors disagreeing with my article.

>So if I'm understanding right, Rocks is re-loading plugins after a sync

It should by default, yes

> but it isn't calling any .setup()s, because it's considered bad practice to initialise your plugin with a function.

Not necessarily because it's bad a practice, but because rocks.nvim follows the unix philosophy of doing one thing well.
We provide separate extensions for things like configuration and lazy-loading.
Hacks for auto-loading `setup` functions are outside the scope of rocks.nvim, but the rocks-config.nvim extension has an option for that. Although I don't think rocks-config.nvim will call any `setup` functions on sync. Only on startup.

**Comment by tombh** [comment]
Ohh that's another reason for `rocks-config.nvim`, I see now. I think that totally makes sense. Do one thing and do it well 💪
