### ISSUE TITLE
:Rocks sync error logging is unhelpful

### ISSUE THREAD

**Issue by sahinf** [nvim-neorocks/rocks.nvim#314]
When user attempts `:Rock sync` but rocks encounters error and [logs](https://github.com/nvim-neorocks/rocks.nvim/blob/bb5203b762af24130505c2ae947c030f719a3a26/lua/rocks/operations/init.lua#L337) it, the log message should be more descriptive than "Sync completed with errors". 
 
```text
ERROR | 2024-05-06 14:48:18 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/init.lua:338 | Sync completed with errors!
```

This error message serves no purpose because I don't know what plugin rocks had an issue with.

**Comment by mrcjkb** [comment]
Hey :wave: 

luarocks can have some quite large error messages, which is why we have a `:Rocks log` command.
I don't think it's useful to try to display the entire error message in the notification, but  maybe a hint to use `:Rocks log` for more details would be a good idea.

**Comment by sahinf** [comment]
Howdy, 

Thanks for responding so fast!
I was actually referring to the output of `:Rocks log`.
For example, this error log after a sync with an error 
![image](https://github.com/nvim-neorocks/rocks.nvim/assets/6597168/29c23737-a3e6-46f9-8310-2678a0b5aca6)

`ERROR | 2024-05-06 15:27:13 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/init.lua:338 | Sync completed with errors!`

What should the user do with this error?

**Comment by sahinf** [comment]
It should log to `:Rocks log` something more useful is what I meant, so the PR doesn't address my issue :(

**Comment by mrcjkb** [comment]
Ah. There should be another log further up.
I've set the default log level to `WARN` in #315. That should make it easier to find.
