### ISSUE TITLE
self install Rocks script failing

### ISSUE THREAD

**Issue by renews** [nvim-neorocks/rocks.nvim#346]
Having an issues when trying to install rocks on a fresh config using the  **Bootstrapping Script**

![CleanShot 2024-05-20 at 11 12 40](https://github.com/nvim-neorocks/rocks.nvim/assets/53726/31e16040-1dd5-4510-a775-acd1070cd828)

on that line

![CleanShot 2024-05-20 at 11 13 39](https://github.com/nvim-neorocks/rocks.nvim/assets/53726/bc26f3dd-d160-4079-9499-bb608224fc43)

**Comment by renews** [comment]
Just to make it clear, I'm on Mac

**Comment by mrcjkb** [comment]
@renews We've been having issues with the x86_64 mac builds on our rocks-binaries server.
That might be what's causing the error message. 
I've been looking into it, but I'm on my mobile right now. 

@MarvinHauke `ENOENT: no such file or directory` is thrown by `vim.system` when the executable you're trying to invoke can't be found. In the bootstrap script, that would most likely be the `luarocks_binary` in your config.

**Comment by renews** [comment]
@mrcjkb Oh =/ Is there any work around this? Thanks for replying!

**Comment by mrcjkb** [comment]
> @mrcjkb Oh =/ Is there any work around this? Thanks for replying!

Not for the bootstrap script. 
I'm trying to fix the rocks-binaries CI.

**Comment by mrcjkb** [comment]
Should be fixed now.

**Comment by renews** [comment]
> Should be fixed now.

And indeed it is! Thanks for the quick fix!
![CleanShot 2024-05-20 at 16 11 21](https://github.com/nvim-neorocks/rocks.nvim/assets/53726/87cc3e81-d993-46d8-a755-1f86786740be)
