### ISSUE TITLE
Feline dependencie failure to install 

### ISSUE THREAD

**Issue by renews** [nvim-neorocks/rocks.nvim#349]
**Context**
I have installed Rocks, Rocks git and Rocks config.
Not sure if this is a rocks-config issue or a rocks issue, sorry for that.

**Step 1**
`:Rocks install feline.nvim`

**Step 2**
Restarted vim and got this error
![CleanShot 2024-05-24 at 15 33 46@2x](https://github.com/nvim-neorocks/rocks.nvim/assets/53726/e06bb769-ee0b-4f17-930e-b2aef7a1cfa5)

I expected here to have webbed icons handled by rocks. 
To make it work, I had to run `:Rocks install nvim-tree/nvim-web-devicons`

After running the install above, this is my tool file
![CleanShot 2024-05-24 at 15 37 12@2x](https://github.com/nvim-neorocks/rocks.nvim/assets/53726/beb3b30b-34d9-467c-9fbf-47d968e11ff5)

Notice that during the install of webdev icons I received the following notification 
![CleanShot 2024-05-24 at 15 39 30@2x](https://github.com/nvim-neorocks/rocks.nvim/assets/53726/3939c5c3-5803-43fd-8dfb-f4328e7d113a)

Not sure if it is a real issue, but hey trying to help.

**Comment by mrcjkb** [comment]
Thanks. This is a feline.nvim issue: https://github.com/freddiehaddad/feline.nvim/pull/84
