### ISSUE TITLE
Fail to update / sync

### ISSUE THREAD

**Issue by boydkelly** [nvim-neorocks/rocks.nvim#369]
I am on a slow 4G network and I get a lot of this on both sync and update.

Failed to update...
Failed to checkout...

Is there some kind of timeout happening that can be adjusted?

![image](https://github.com/nvim-neorocks/rocks.nvim/assets/3412972/50e850c3-4ecc-4033-bfb6-87c2e2310809)
![image](https://github.com/nvim-neorocks/rocks.nvim/assets/3412972/b80b9e23-50ab-42d5-aa48-8304bd72df24)

**Comment by mrcjkb** [comment]
Hey :wave: 

We don't set any timeouts. You can check `:Rocks log`, but it's likely that the `luarocks` and `git` commands which are failing.
rocks.nvim [does allow to override the luarocks config](https://github.com/nvim-neorocks/rocks.nvim/pull/334), but I don't know if there are any connection timeout configs you can set.
rocks-git just uses your git client.

**Comment by boydkelly** [comment]
ok got it.  @erichards [baredot.nvim](https://github.com/ejrichards/baredot.nvim) sets the GIT_DIR and GIT_WORK_TREE env vars, and this seems to cause the issue.   I can just toggle baredot off.   Thanks!!!
