### ISSUE TITLE
[macos] bundled luarocks install doesn't pick up `LUA_PATH`

### ISSUE THREAD

**Issue by arepavich** [nvim-neorocks/rocks.nvim#373]
Hello 👋

I found myself needing to reinstall rocks.nvim today, and I'm now bumping up against errors with luarocks.

After purging my `~/.local/share/nvim/rocks` and `~/.local/share/nvim/site/pack` directories, I ran the install script with `nvim -u NORC -c "source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"` and replaced my init.lua contents with the updated version delivered with the script.

The install script seemed to execute properly; however, when I subsequently closed and reopened neovim to pick up my config, I was immediately met with errors.

## Logs
On inspection of the rocks logs, it appears that luarocks is failing on initialization as it cannot find any of its library within the path. As such, I suspect this may just be a path configuration issue, but my limited knowledge of lua has me throwing in the towel for the night.

### Log contents

```
[START][2024-06-08 21:59:05] rocks.nvim logging initiated
ERROR | 2024-06-08 21:59:11 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:64 | luarocks CLI FAILED
ERROR | 2024-06-08 21:59:11 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:65 | /opt/homebrew/bin/luajit: ...ks/lib/luarocks/rocks-5.1/luarocks/3.11.1-1/bin/luarocks:4: module 'luarocks.core.cfg' not found:
	no field package.preload['luarocks.core.cfg']
	no file '/var/folders/zx/l7spnsn56w53d447n3fg6r7c0000gn/T/nvim.arepavich/yRN9V3/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/cfg.lua'
	no file './luarocks/core/cfg.lua'
	no file '/opt/homebrew/share/luajit-2.1/luarocks/core/cfg.lua'
	no file '/usr/local/share/lua/5.1/luarocks/core/cfg.lua'
	no file '/usr/local/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file '/opt/homebrew/share/lua/5.1/luarocks/core/cfg.lua'
	no file '/opt/homebrew/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file '/Users/arepavich/.luarocks/share/lua/5.1/luarocks/core/cfg.lua'
	no file '/Users/arepavich/.luarocks/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file '/var/folders/zx/l7spnsn56w53d447n3fg6r7c0000gn/T/nvim.arepavich/yRN9V3/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file './luarocks/core/cfg.so'
	no file '/usr/local/lib/lua/5.1/luarocks/core/cfg.so'
	no file '/opt/homebrew/lib/lua/5.1/luarocks/core/cfg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/arepavich/.luarocks/lib/lua/5.1/luarocks/core/cfg.so'
	no file '/var/folders/zx/l7spnsn56w53d447n3fg6r7c0000gn/T/nvim.arepavich/yRN9V3/luarocks-CB511A84450400/lib/lua/5.1/luarocks/core/cfg.so'
	no file './luarocks.so'
	no file '/usr/local/lib/lua/5.1/luarocks.so'
	no file '/opt/homebrew/lib/lua/5.1/luarocks.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/arepavich/.luarocks/lib/lua/5.1/luarocks.so'
	no file '/var/folders/zx/l7spnsn56w53d447n3fg6r7c0000gn/T/nvim.arepavich/yRN9V3/luarocks-CB511A84450400/lib/lua/5.1/luarocks.so'
stack traceback:
	[C]: in function 'require'
	...ks/lib/luarocks/rocks-5.1/luarocks/3.11.1-1/bin/luarocks:4: in main chunk
	[C]: at 0x01025e66dc

... (Truncated for brevity - original output contained two more stack traces identical to this one)
```

**Comment by mrcjkb** [comment]
Hey 👋 

There was [a recent change where we now bundle luarocks with rocks.nvim as a dependency](https://github.com/nvim-neorocks/rocks.nvim/pull/340) so that we can ensure a compatible version is installed.

It looks like your bundled installation isn't picking up the `LUA_PATH` properly.

I'll look into fixing this later today (probably by setting the `LUA_PATH` before invoking luarocks).

In the meantime, you can work around this by setting `vim.g.rocks_nvim.luarocks_binary` to another luarocks installation.

**Comment by arepavich** [comment]
Thanks for the ideas to workaround it! I've been digging into this some more today and, while it wasn't entirely straightforward, I did manage to get rocks installed and functioning again by doing the following:

1. Remove `~/.local/share/nvim/rocks` and `~/.local/share/nvim/site/pack/luarocks` directories:
2. Set init.lua per the [manual installation instructions](https://github.com/nvim-neorocks/rocks.nvim/wiki/Installing-rocks.nvim-manually,-without-the-installation-script) (I kept the additional `.dylib` and `.dll` cpath entries, though I don't know if this would affect the outcome.
3. Add the following to init.lua:
```
vim.env.LUA_PATH = package.path
vim.env.LUA_CPATH = package.cpath
```
4.  Run `luarocks --lua-version=5.1 --tree <rocks_path> --server='https://nvim-neorocks.github.io/rocks-binaries/' install rocks.nvim` per the [manual installation instructions](https://github.com/nvim-neorocks/rocks.nvim/wiki/Installing-rocks.nvim-manually,-without-the-installation-script).
