### ISSUE TITLE
[Bug] Bundled luarocks fails with "luarocks.core.cfg not found" if temporary bootstrap luarocks install is removed 

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#377]
https://github.com/nvim-neorocks/rocks.nvim/pull/376

**Comment by mrcjkb** [comment]
@TarunDaCoder this should be fixed with the latest update. You may need to manually update if luarocks is broken for you :disappointed: 

Sorry about that.

**Comment by TarunDaCoder** [comment]
@mrcjkb Oh ok, thanks :D
