### ISSUE TITLE
[feature] allow user to use system-side luarocks without install another

### ISSUE THREAD

**Issue by Freed-Wu** [nvim-neorocks/rocks.nvim#379]
https://github.com/nvim-neorocks/rocks.nvim/blob/master/bootstrap.lua#L110 call set_up_luarocks() to install another luarocks whatever if user have one.

How about allowing user to use system-side luarocks? It can save time and network bandwidth.

TIA!

**Comment by mrcjkb** [comment]
Duplicate of #218
