### ISSUE TITLE
[Health] Error if nvim-treesitter and a luarocks tree-sitter-parser are both installed

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#415]
...and recommend nvim-treesitter-legacy-api instead

**Comment by teto** [comment]
does it make sense to upload `nvim-treesitter-legacy-api` as `nvim-treesitter` on luarocks.org . Just until we get something better
?

**Comment by mrcjkb** [comment]
> does it make sense to upload `nvim-treesitter-legacy-api` as `nvim-treesitter` on luarocks.org . Just until we get something better

The issue is that people might install the `master` branch of nvim-treesitter using rocks-git.
