### ISSUE TITLE
[CI] Disable PR checklist bot for regular contributors 

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#428]
I find the github action bot pretty noisy. Can it be disabled for contributors of the repo already ? they should know the rules already.

_Originally posted by @teto in https://github.com/nvim-neorocks/rocks.nvim/issues/423#issuecomment-2196453272_

**Comment by teto** [comment]
or instead replace it with a MR template like on nixpkgs.

**Comment by mrcjkb** [comment]
Disabled for anyone who has contributed before https://github.com/nvim-neorocks/rocks.nvim/commit/2c5d242b112fe53eec1ed65b3889e6eba7c7caef

This needs to be applied to all our modules, which I will do another time.

> or instead replace it with a MR template like on nixpkgs.

I'm not a fan of PR templates, because they're easier to ignore.

**Comment by teto** [comment]
thanks for doing so o/
