### ISSUE TITLE
checkhealth has redundant output

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/rocks.nvim#429]
with rocks 2.31 `checkhealth rocks`  gives:
```
Checking rocks.toml ~
- OK No errors found in rocks.toml.
- OK No errors found in rocks.toml.
- OK No errors found in rocks.toml.
- OK No errors found in rocks.toml.
- OK No errors found in rocks.toml.
- OK No errors found in rocks.toml.
```
my rocks.toml:
```
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
# "rocks.nvim" = "2.19.0" # rocks.nvim can also manage itself :D
cmp-rg = "1.3.9"
"oil.nvim" = "2.10.0"
# -- :DiffviewOpen
"diffview.nvim" = "scm"
"haskell-tools.nvim" = "3.1.10"
"none-ls.nvim" = "scm"
"bufferline.nvim" = "4.6.1"

[config]
plugins_dir = "plugins/"
```

I think I would like maybe a more in detail command, like `:Rocks debug` or `:Rocks check` that displays the path towards LUAROCKS_CONFIG, luarocks --version and so on. Maybe the rocks.nvim extensions too if there is a way to identify those.

**Comment by mrcjkb** [comment]
The redundant output is a bug. 

> I think I would like maybe a more in detail command, like :Rocks debug or :Rocks check that displays the path towards LUAROCKS_CONFIG, luarocks --version and so on. Maybe the rocks.nvim extensions too if there is a way to identify those.

Why not put all of that in the health check?

**Comment by teto** [comment]
I am not sure there is a definite official policy on it but my vision of checkhealth is that it should remain minimal and actionable.

For instance nvim-treesitter checkhealth dumps the OS, your CPU etc but if every plugin does the same it doesn't scale.

LUAROCKS_CONFIG seems like an internal aspect that a user could do nothing about.

**Comment by mrcjkb** [comment]
> For instance nvim-treesitter checkhealth dumps the OS, your CPU etc but if every plugin does the same it doesn't scale.

Sure, but that's not what I'm proposing. 

We actually generate a luarocks config that we pass to the `luarocks` CLI invocation. Making sure it can be picked up properly could be a nice addition to the health check.

I want to be careful about adding too many `Rocks` subcommands; it could become overwhelming. Especially if there's both a `log` and a `debug` command.

Some debug info could just be dumped into the log file the first time `Rocks log` is called.
That would be useful because people often paste the log file when opening issues.
