### ISSUE TITLE
Failed to write rockspec file: No such file or directory

### ISSUE THREAD

**Issue by NETLIFYHOSTINGAHMD** [nvim-neorocks/rocks.nvim#438]
![2024-06-30-130010_1259x146_scrot](https://github.com/nvim-neorocks/rocks.nvim/assets/65476194/72d3fba5-d8c0-4bf7-9cf3-90a951c69823)

I get this error when trying to install the kanagawa.nvim by :Rocks install kanagawa.nvim.

So far I have tried writing the fulll plugin name rebelot/kanagawa, and executing :RocksInstall instead.

Configuration:
   Lua:
      Version    : 5.3
      LUA        : /usr/bin/lua5.3 (ok)
      LUA_INCDIR : /usr/include/lua5.3 (ok)
      LUA_LIBDIR : /usr/lib64 (ok)

   Configuration files:
      System  : /etc/luarocks/config-5.3.lua (ok)
      User    : /home/ahmed/.luarocks/config-5.3.lua (not found)

   Rocks trees in use:
      /home/ahmed/.luarocks ("user")
      /usr ("system")

## My init.lua:

```vim.opt.termguicolors = false
-- Adapted from https://github.com/folke/lazy.nvim#-installation
-- Install lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Set up both the traditional leader (for keymaps) as well as the local leader (for norg files)
vim.g.mapleader = " "
vim.g.maplocalleader = ","

require("lazy").setup({
  {
    
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },
      highlight = { enable = true },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
  {
      "vhyrro/luarocks.nvim",
      priority = 1000,
      config = true,
  },
  {
    "nvim-neorg/neorg",
    dependencies = { "luarocks.nvim" },
    version = "*",
    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.concealer"] = {},
          ["core.dirman"] = {
            config = {
              workspaces = {
                notes = "~/notes",
		DotComSecrets = "~/notes/DotComSecrets",
              },
              default_workspace = "notes",
            },
          },
        },
      }

      vim.wo.foldlevel = 99
      vim.wo.conceallevel = 2
    end,
  }
})
```

**Comment by mrcjkb** [comment]
Hey :wave:

I'm very confused 😅 . `:Rocks install` is a rocks.nvim command, but it looks like you're using lazy.nvim.

How is that command doing anything for you at all?

**Comment by NETLIFYHOSTINGAHMD** [comment]
my bad lol

**Comment by NETLIFYHOSTINGAHMD** [comment]
now it works I didn't realize I wasn't using rocks.nvim

**Comment by NETLIFYHOSTINGAHMD** [comment]
> Hey 👋
> 
> I'm very confused 😅 . `:Rocks install` is a rocks.nvim command, but it looks like you're using lazy.nvim.
> 
> How is that command doing anything for you at all?
> 
> Edit: luarocks.nvim has a `RocksInstall` command, so you'll want to ask there.

probaby because I tried to install rocks.nvim before
