### ISSUE TITLE
[Feature] Ability to pass extra luarocks installation args

### ISSUE THREAD

**Issue by SuperBo** [nvim-neorocks/rocks.nvim#439]
Hi, when installing https://github.com/SuperBo/fugit2.nvim with Rocks `:Rocks install fugit2.nvim`. I met these errors.

```
Error: Could not find library file for GIT2
  No file /git2/lib/libgit2.dylib in /usr/local/lib
  No file /git2/lib/libgit2.dylib in /usr/local
  No file libgit2.tbd in /usr/local/lib
  No file libgit2.tbd in /usr/local
  No file libgit2.a in /usr/local/lib
  No file libgit2.a in /usr/local
  No file libgit2.dylib in /usr/local/lib
  No file libgit2.dylib in /usr/local
  No file matching libgit2.so.* in /usr/local/lib
  No file matching libgit2.so.* in /usr/local
  No file /git2/lib/libgit2.dylib in /usr/lib
  No file /git2/lib/libgit2.dylib in /usr
  No file libgit2.tbd in /usr/lib
  No file libgit2.tbd in /usr
  No file libgit2.a in /usr/lib
  No file libgit2.a in /usr
  No file libgit2.dylib in /usr/lib
  No file libgit2.dylib in /usr
  No file matching libgit2.so.* in /usr/lib
  No file matching libgit2.so.* in /usr
  No file /git2/lib/libgit2.dylib in /lib
  No file /git2/lib/libgit2.dylib in /
  No file libgit2.tbd in /lib
  No file libgit2.tbd in /
  No file libgit2.a in /lib
  No file libgit2.a in /
  No file libgit2.dylib in /lib
  No file libgit2.dylib in /
  No file matching libgit2.so.* in /lib
  No file matching libgit2.so.* in /
  No file /git2/lib/libgit2.dylib in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
  No file /git2/lib/libgit2.dylib in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr
  No file libgit2.tbd in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
  No file libgit2.tbd in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr
  No file libgit2.a in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
  No file libgit2.a in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr
  No file libgit2.dylib in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
  No file libgit2.dylib in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr
  No file matching libgit2.so.* in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
  No file matching libgit2.so.* in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr
  No file /git2/lib/libgit2.dylib in /usr/local/opt/lib
  No file /git2/lib/libgit2.dylib in /usr/local/opt
  No file libgit2.tbd in /usr/local/opt/lib
  No file libgit2.tbd in /usr/local/opt
  No file libgit2.a in /usr/local/opt/lib
  No file libgit2.a in /usr/local/opt
  No file libgit2.dylib in /usr/local/opt/lib
  No file libgit2.dylib in /usr/local/opt
  No file matching libgit2.so.* in /usr/local/opt/lib
  No file matching libgit2.so.* in /usr/local/opt
You may have to install GIT2 in your system and/or pass GIT2_DIR or GIT2_LIBDIR to the luarocks command.
Example: luarocks install fugit2.nvim GIT2_DIR=/usr/local
```

I want to install fugit2.nvim with custom GIT2_DIR or GIG2_LIBDIR. How can I achieve this with `:Rocks` command.

**Comment by mrcjkb** [comment]
Hey :wave: 

I don't think we currently support that. But it should be possible to implement something for

```toml
[plugins."fugit2.nvim"]
version = "1.0.0"
install_args = [
  "GIT2_DIR=/some/path"
]
```

We would probably be faster to support it in rocks.toml only initially (so you'd have to enter it manually and then install it with `:Rocks sync`).
And then later we could find a nice way to pass the `install_args` to `:Rocks install`.

@vhyrro what are your thoughts on this?

**Comment by vhyrro** [comment]
As an initial implementation `install_args` looks good to me.
This whole issue gave me an idea - I was wondering whether we should allow arbitrary `key=value` pairs in the invocation of `:Rocks install`. For instance, allowing `:Rocks install something opt=true ft=markdown` and feeding that directly into the toml.

**Comment by SuperBo** [comment]
@vhyrro, I think those ARGS must be provided via luarocks args and is not env variables.

So I will disable `external dependencies` in the plugin first while wating for the `rocks.nvim` supports for extra args.

Refs:
  - https://github.com/luarocks/luarocks/wiki/Platform-agnostic-external-dependencies

**Comment by mrcjkb** [comment]
> For instance, allowing :Rocks install something `opt=true` `ft=markdown` and feeding that directly into the toml.

We already do that[^1] :wink: 

[^1]: As long as the extensions know how to parse args that rocks.nvim doesn't know about.
       So far, only rocks.nvim and rocks-git.nvim know how to parse args.

What could be tricky is coming up with a good API for args that are lists:

```vim
:Rocks install {rock} opt=true install_args=["GIT2_DIR=/some/path","foo","bar"]
```

or

```vim
:Rocks install {rock} opt=true install_args=[GIT2_DIR=/some/path,foo,bar]
```

or, assuming any args that rocks.nvim can't parse are `install_args`:

```vim
:Rocks install {rock} opt=true GIT2_DIR=/some/path
```

The last one is more concise, but also more brittle: If someone passes in `ft=markdown`, it would be added to the `install_args` as long as rocks-lazy.nvim doesn't register an arg parser.

> should we instead support an [env] section in the toml, which would modify vim.env?

Luarocks won't pick up `GIT2_DIR` from an environment variable. It has to be passed as an arg to `install`.

**Comment by vhyrro** [comment]
Oh wow, I didn't even know we did generic parsing of arguments like that.

If env variables don't cut it (why, luarocks, why?), then I'm all for `install_args`. I wouldn't worry about parsing them inline for the time being, it'll become very complicated very quick.

**Comment by SuperBo** [comment]
@mrcjkb, thank you for quick fix. When will you release a new version with this fix?

**Comment by mrcjkb** [comment]
> @mrcjkb, thank you for quick fix. When will you release a new version with this fix?

Just waiting for a review from one of the other maintainers 😄

**Comment by teto** [comment]
rather than 
```
[plugins."fugit2.nvim"]
version = "1.0.0"
install_args = [
  "GIT2_DIR=/some/path"
]
```
shouldn't we set those in the luarocks config instead so it becomes available to all plugins ? and by "we" I actually mean the user because it's platform specific. Via somethling like `vim.g.rocks_nvim.luarocks_external_dependencies`

**Comment by vhyrro** [comment]
> rather than 
> ```
> [plugins."fugit2.nvim"]
> version = "1.0.0"
> install_args = [
>   "GIT2_DIR=/some/path"
> ]
> ```
> shouldn't we set those in the luarocks config instead so it becomes available to all plugins ? and by "we" I actually mean the user because it's platform specific. Via somethling like `vim.g.rocks_nvim.luarocks_external_dependencies`

Luarocks permits providing flags on a per-install basis via `luarocks install`, so it makes sense to permit per-rock configs :)

**Comment by mrcjkb** [comment]
It would be neat if you could set them globally by default or via an environment variable.
But that's a luarocks issue. As long as luarocks doesn't support it, I don't feel comfortable hacking it into rocks.nvim.
