### ISSUE TITLE
Linux: installation script fails due to lack of actual version of toml-edit binary

### ISSUE THREAD

**Issue by user529** [nvim-neorocks/rocks.nvim#440]
First of all, allow me to express my deepest thanks for the installation script. It makes the installation process way easier. 
However, the installation process on Linux is not as smooth as it could be.

The reason is toml-edit dependency. As soon as the luarocks realizes the toml-edit should be installed, it somehow detects that the latest version is 0.4.1 and tries to find it https://nvim-neorocks.github.io/rocks-binaries/. But fails, due to only 0.3.6 is available for Linux. So it goes to luarocks.org, takes the dependency from there, and tries to compile it using Cargo. In case there is no Rust+Cargo, then installation failed.

As a workaround, it's possible to install toml-edit 0.3.6 from the rocks-binaries folder manually or compile toml-edit 0.4.1 with the Cargo (if you have one).

On the other hand, I believe, it would be enough to just put the appropriate toml-edit binary for Linux into the rocks-binaries folder.

As an alternative. Not sure if it could be overcome with
`luarocks ... --only-server='https://nvim-neorocks.github.io/rocks-binaries/' install ...`.
I don't know whether the version of dependency can be downgraded in case the latest is not found. But even if it works, in that case, you will have to keep all the necessary dependencies (including dependencies of dependencies) for all supported architectures up-to-date in the rocks-binaries folder. And that probably doesn't sound like a good approach.

**Comment by mrcjkb** [comment]
Hey :wave: 

thanks for reporting :pray: 

Something seems to be wrong with our rocks-binaries CI.
I've just added the latest toml-edit manually and will look into fixing the CI.

**Comment by mrcjkb** [comment]
Fixed.

https://github.com/nvim-neorocks/rocks-binaries/actions/runs/9747960858/job/26901861168
