### ISSUE TITLE
ask the user if the installer should install the rocks.nvim extensions ?

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/rocks.nvim#457]
The installer could ask: 
```
rocks.nvim only allows to install packages available at www.luarocks.org .
Do you want to install all rocks.nvim extensions (=vim plugins) to benefit from:
- installation of plugins only available via git
- lazyloading
- automatic loading of configuration
```

I think a newcomer would definitely say yes and it could help with onbarding. Advanced users are free to do without. Alternatively it could be a message after rocks.nvim installation that asks: `Do you want to run ":Rocks install rocks-git.nvim rocks-config.nvim ..." to be able to ...` ?

NB: not something I intend to work on as I dont use the installer. So feel free to close if not interested.

**Comment by mrcjkb** [comment]
Potential duplicate of https://github.com/nvim-neorocks/rocks.nvim/issues/93?

**Comment by teto** [comment]
indeed
