### ISSUE TITLE
Feature request: fuzzy completion on `:Rocks install`

### ISSUE THREAD

**Issue by NTBBloodbath** [nvim-neorocks/rocks.nvim#46]
Currently we have a pretty decent _and performant_ tab completion for all the available rocks on Luarocks while installing a new plugin, however, it doesn't work with keywords as we are using `vim.startswith` to filter rocks based on the user query (e.g. `:Rocks install nvim` will filter rocks that starts with `nvim` for completion).

However, we could highly improve it by adding some fuzzy filtering with [fzy-lua](https://github.com/swarn/fzy-lua) which is also in Luarocks so we could easily add it as a dependency for `rocks.nvim` so instead of only matching rocks starting with `nvim` we could match any rock that contains `nvim` on its name.

**Comment by mrcjkb** [comment]
Closed by #49
