### ISSUE TITLE
Long startuptime due to `rocks.lua`

### ISSUE THREAD

**Issue by austinliuigi** [nvim-neorocks/rocks.nvim#463]
Using [`vim-startuptime`](https://github.com/dstein64/vim-startuptime) to profile the time it takes to source files on startup, it shows that `rocks.lua` is taking over half a second to source, which is over 80% of the overall time it takes to start up for me. This causes a noticeable delay from the time I run `nvim` to when the initial screen refreshes. Is this expected and/or avoidable? Other than this, I'm really enjoying the plugin! :)

</br>

![image](https://github.com/nvim-neorocks/rocks.nvim/assets/85013922/b47389d8-54d5-4071-a61d-78aa383a5d89)

**Comment by mrcjkb** [comment]
Hey 👋 

vim-startuptime isn't a very good way of measuring the impact of rocks.nvim itself.

`rocks.lua` calls `:h packadd` on all of your plugins that are configured to load eagerly. The time you're seeing includes the impact of all the plugins it's managing.

**Comment by mrcjkb** [comment]
It looks like you [can press `K` on events to get additional info](https://github.com/dstein64/vim-startuptime?tab=readme-ov-file#usage).
