### ISSUE TITLE
Windows: pcall causing terminals to rapidly open/close

### ISSUE THREAD

**Issue by MeguminSama** [nvim-neorocks/rocks.nvim#513]
I just installed rocks for the first time. Windows 11, using Windows Terminal (both PowerShell 7.4.5 & Command Prompt).

When I open nvim with rocks enabled, it causes new terminal windows to appear and disappear rapidly, making it impossible to work or even type `:q`.

After some debugging, it seems it is caused by setting `opts.detach = true` in the pcall in `luarocks.lua`. After setting this to false, the terminals stopped flashing.

Since it seems this was intentional (`Prevent luarocks from exiting uncleanly`), perhaps there's an alternative way to get a similar effect, without causing new terminal windows to open and close?

https://github.com/nvim-neorocks/rocks.nvim/blob/ce6e2bde1a786a2b8b657467f000f8443abc9ce6/lua/rocks/luarocks.lua#L89-L91

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the detailed report and debugging. 🙏 

I think the only thing we can do here is to set it to `false` on Windows.
