### ISSUE TITLE
[Module]: `rocks-lsp` module for rocks.toml

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#52]
- Diagnostics for outdated rocks
- Code actions to update/downgrade a rock
- Completions, e.g. for rocks and versions
- Hover: `luarocks show`

Maybe this should be implemented as an external module?

**Comment by NTBBloodbath** [comment]
Sounds good to me as an external module, could be integrated with the UI when done. I was just thinking about doing something like `:Rocks list` and having something like that.

**Comment by vhyrro** [comment]
Instead of calling this `rocks-lsp`, I've been considering giving it an alternate, less confusing name (`rocks-hints` maybe?).

`rocks-lsp` implies that it's a module for setting up language servers, which it obviously isn't :sweat_smile:

**Comment by mrcjkb** [comment]
https://github.com/nvim-neorocks/rocks-edit.nvim

Closing as completed.
