### ISSUE TITLE
vim.treesitter.langauge.add("org") fails even if TS parser is already installed.

### ISSUE THREAD

**Issue by bodby** [nvim-neorocks/rocks.nvim#520]
This seems to happen because it doesn't detect the org parser. In config/init.lua:
```lua
function Config:install_grammar()
  local ok = pcall(vim.treesitter.language.add, 'org')
  if ok then
    return
  end
  require('orgmode.utils.treesitter.install').run()
end
```
`.run()` clones the orgmode parser but then returns an error. The problem is that the parser is already installed as a plugin; it's just that any files that run at startup can't seem to find it. Running `:lua vim.treesitter.language.add("org")` works just fine, but if put into e.g init.lua it returns an error saying the parser couldn't be found.
I've also tried setting `opt = true` and then manually setting up the plugin, but still run into the same issue.
This doesn't happen with lazy.nvim.

**Comment by bodby** [comment]
Seems to be an issue with the rtp. Adding manually fixes it. I'm using the manual installation:
```lua
local luarocks_cpath = {
	vim.fs.joinpath(rocks_config.rocks_path,
	"lib", "lua", "5.1", "?.so"),
	vim.fs.joinpath(rocks_config.rocks_path,
	"lib64", "lua", "5.1", "?.so"),
}
```
while the actual parser is installed in rocks_config.rocks_path/lib/luarocks/rocks-5.1/tree-sitter-orgmode/.
Adding `vim.opt.runtimepath:append(vim.fs.joinpath(vim.fn.stdpath("data"), "rocks", "lib", "luarocks", "rocks-5.1", "tree-sitter-*", "*"))` as an extra line in `init.lua` works for now.

**Comment by mrcjkb** [comment]
hey 👋 

thanks for reporting and thanks for the workaround. 🙏

rocks.nvim uses a `plugin` script to initialise the packages it manages, which is why the parsers aren't on the runtimepath by the time Neovim sources your init.lua.

It's strange, Neovim can find colorschemes on `site/pack/*/opt`, but not autoload scripts or tree-sitter parsers.
