### ISSUE TITLE
README file suggestion

### ISSUE THREAD

**Issue by dfgordon** [nvim-neorocks/rocks.nvim#550]
Requesting clarification of this snip from the README:

"A lua 5.1 or luajit installation, including headers (for luarocks). Note that Lua must be executable using the lua command."

It starts out fine, one thing or the other, but then by then end the "other thing" seems to be required after all (the "or" got transformed into an "and").  The strange thing is it seems everything works if typing `lua` executes *any* Lua, such as Lua 5.4, *and* luajit is installed.  This is not made clear, and if true, is a useful thing to know.

Regarding headers, I can't tell if this refers to Lua 5.1 headers needed for luarocks, luajit headers needed for luarocks, or luarocks headers needed for something else.  I didn't do anything special about headers and things worked, perhaps they already were installed.  In any case can we clarify what these headers are about?

**Comment by mrcjkb** [comment]
Hey 👋 

> but then by then end the "other thing" seems to be required after all (the "or" got transformed into an "and").

I suppose you're referring to the fact that Lua must be executable using the lua command?
What that means is that luarocks expects to find a `lua` executable on the path. 
On some systems (e.g. when using homebrew on macos), if you have luajit installed, you can only run it with the `luajit` command, not with the `lua` command.

This will be solved (and the note can then be removed) when #386 has been implemented.

> Regarding headers, I can't tell if this refers to Lua 5.1 headers needed for luarocks, luajit headers needed for luarocks, or luarocks headers needed for something else. 

Yep, I can see how the wording is confusing there. I'll update that.
To clarify: Some luarocks packages are written in C and built against the Lua headers. Not all distractions ship Lua with headers included. 

We have shifted out focus to writing our own luarocks package manager (#539), which is capable of installing lua (+ headers).

**Comment by dfgordon** [comment]
OK good to know.  The below is what I have and it works fine for whatever reason.  It sounds like this will be a moot point later on.  Thanks for `rocks.nvim`!

(base) ➜  ~ which lua
/opt/homebrew/bin/lua
(base) ➜  ~ which luajit
/opt/homebrew/bin/luajit
(base) ➜  ~ lua -v
Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio
(base) ➜  ~ luajit -v
LuaJIT 2.1.1725453128 -- Copyright (C) 2005-2023 Mike Pall. https://luajit.org/
(base) ➜  ~
