### ISSUE TITLE
Parser dependencies don't start automatically

### ISSUE THREAD

**Issue by flexagoon** [nvim-neorocks/rocks.nvim#561]
On some parsers (I currently found `astro` and `php` to be affected) highlighting doesn't work when you open a file. It sometimes starts working after restarting treesitter or switching a file, but sometimes doesn't.

Easiest way to reproduce:

```php
<?php

echo "Hello World!";
```

When you open this file with treesitter highlighting enabled, it looks like this:

![image](https://github.com/user-attachments/assets/edf9bc1c-60d8-4fd2-ac0d-70878d251dde)

However, after running `:lua vim.treesitter.stop(); vim.treesitter.start()`:

![image](https://github.com/user-attachments/assets/8958fcf0-543f-4f89-9d44-6649d2dcc8e2)

**Comment by mrcjkb** [comment]
Just tried it out. It works fine on my end with `tree-sitter-typescript`, but not with `tree-sitter-php`. For `tree-sitter-php`, I have to manually install `tree-sitter-php_only`.
