### ISSUE TITLE
rocks.nvim "floods" /tmp with cache

### ISSUE THREAD

**Issue by quadraplat** [nvim-neorocks/rocks.nvim#578]
Floods is a bit of an understatement, but each time I run nvim, a folder named luarocks_local_cache-<7 random numbers> is created in /tmp.  These folders are all 3.1M large, which isn't much, but overtime, this becomes quite large, especially if /tmp is not mounted as a tmpfs.

Perhaps rocks.nvim should either clean this folder up on closure or attempt to reuse it when a new instance of nvim is opened?

**Comment by mrcjkb** [comment]
Hey 👋 

Sorry for the late response.
This is a luarocks issue. I will close this issue, as we will be moving away from luarocks.

See:
- #539

**Comment by Dynge** [comment]
Any known workarounds? I have a 6GB /tmp folder that gets filled in a matter of minutes.

**Comment by mrcjkb** [comment]
> Any known workarounds? I have a 6GB /tmp folder that gets filled in a matter of minutes.

Afaik, there's no way to disable caching in luarocks - you'd have to ask for that in [the luarocks repo](https://github.com/luarocks/luarocks/).

You can, however, override the luarocks cache location via the rocks.nvim config:

```lua
vim.g.rocks_nvim = {
  -- ...
  luarocks_config = {
    local_cache = vim.fs.joinpath(vim.fn.stdpath("cache"), "luarocks"), 
  },
}
```

(Note: I haven't tested this, it may need some tweaking).

**Comment by mrcjkb** [comment]
Actually, it's probably a good idea for rocks.nvim to configure luarocks to use the nvim cache directory: #718.
