### ISSUE TITLE
Error when installing tree-sitter-comment

### ISSUE THREAD

**Issue by flexagoon** [nvim-neorocks/rocks.nvim#579]
When trying to install tree-sitter-comment, it shows the following error:

![image](https://github.com/user-attachments/assets/fe4c125c-d965-4be6-9ffa-7080bf60eb3c)

After which, the installation just hangs and doesn't complete

**Comment by ambaradan** [comment]
Same error with `treesitter_markdown_inline`, and again the installation must be aborted as it does not terminate. (Rocky Linux 9.4)
![inline_install_error](https://github.com/user-attachments/assets/8118fb25-74c9-4231-a3d6-de9bea5aec81)

**Comment by ambaradan** [comment]
Manually inserted into **rocks.toml** generates the following error with a `:Rocks sync` while a `:Rocks update` fixes the problem with treesitter_markdown_inline but produces an error with treesitter-jsonc
![inline_sync_error](https://github.com/user-attachments/assets/e30c4179-acad-4ef2-b6ef-64d231c0bef2)

**Comment by ambaradan** [comment]
With these parsers, my configuration performs the `sync` correctly.

```txt
# NOTE: tree-sitter parsers
tree-sitter-bash = "scm"
tree-sitter-css = "scm"
tree-sitter-git_config = "scm"
tree-sitter-git_rebase = "scm"
tree-sitter-gitattributes = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-html = "scm"
tree-sitter-ini = "scm"
tree-sitter-json = "scm"
# tree-sitter-jsonc = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-markdown = "scm"
# tree-sitter-markdown_inline = "scm"
tree-sitter-regex = "scm"
tree-sitter-toml = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-yaml = "scm"
```
