### ISSUE TITLE
Feature request: Install local plugins

### ISSUE THREAD

**Issue by TarunDaCoder** [nvim-neorocks/rocks.nvim#583]
Hey!

I don't know if this exists already, but I was wondering about the support for installing plugins that exist locally on your system instead of on Luarocks or GitHub.
If this already exists I'm sincerely sorry for wasting your time.

Thanks

**Comment by mrcjkb** [comment]
https://github.com/nvim-neorocks/rocks-dev.nvim 😄

**Comment by TarunDaCoder** [comment]
Thanks a lot Marc! Didn't see that one 😅
