### ISSUE TITLE
Support newer lua versions

### ISSUE THREAD

**Issue by Rixtho** [nvim-neorocks/rocks.nvim#585]
Is there a reason why only lua 5.1 is supported? My distro only comes with lua 5.4 and I would have to build lua myself to use 5.1. It would be nice if I don't have to do this.

Reference in install script:  [installer.lua](https://github.com/nvim-neorocks/rocks.nvim/blob/a3143d06ce90440c92a0bd303906dd110ce35fc6/installer.lua#L423)

**Comment by mrcjkb** [comment]
because Neovim ships with luajit or lua 5.1 (depending on the distro).
To be able to build native luarocks libraries with lua 5.1 compatibility, you need lua 5.1 headers.
For most purposes, you can use lua 5.4 to run luarocks, but you may run into problems if you try to install native libraries.

**Comment by Rixtho** [comment]
Does neovim also ship with the headers? If so why doesn't rocks.nvim find them during installation?

**Comment by mrcjkb** [comment]
No, Neovim doesn't ship with Lua headers.
