### ISSUE TITLE
Running `Rocks sync` from bootstrap script

### ISSUE THREAD

**Issue by tombh** [nvim-neorocks/rocks.nvim#612]
Should it be possible to run something like `vim.cmd.Rocks("sync")` after the bootstrap script is successful? I've tried but I get "command not found: Rocks".

I can of course run `:Rocks sync` once Neovim starts. But it'd just be nice to automate it.

**Comment by mrcjkb** [comment]
Potentially a duplicate of #293?

**Comment by tombh** [comment]
Indeed, thank you.
