### ISSUE TITLE
[Feature] Add newly installed plugins to runtimepath

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks.nvim#79]
At the end of `Rocks install`, and `Rocks sync`, add the newly added plugins to the runtime path.

Perhaps this should be configurable?

**Comment by vhyrro** [comment]
Yep adding this behind a config option sounds good! Perhaps enabled by default even :)

**Comment by NTBBloodbath** [comment]
> Yep adding this behind a config option sounds good! Perhaps enabled by default even :)

This. That would allow you to use the rocks directly without having to relaunch Neovim, right?

**Comment by mrcjkb** [comment]
> > Yep adding this behind a config option sounds good! Perhaps enabled by default even :)
> 
> This. That would allow you to use the rocks directly without having to relaunch Neovim, right?

That's what I'm hoping

**Comment by vhyrro** [comment]
Merged as part of #82!
